### ISSUE TITLE
User cannot access app after first Login

### ISSUE THREAD

**Issue by chhavip** [systers/conference-android#33]
**Description**
As an attendee, 
I cannot access the application after first login,
The login screen should be skipped

**Mocks**
![19578867_10209180247370449_2019720035_o](https://user-images.githubusercontent.com/7212638/27674028-7140bc44-5cc1-11e7-8e91-5bf592962547.jpg)

**Acceptance Criteria**
- Login Screen is skipped after first login
- User details are saved after first login and it is established that they have logged in
- If User Logs Out, the Login Screen should be presented again on next opening of applicaiton

**Definition of Done**
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Approved by UI team.
- Able to show feature in demo.

**Estimation**
- 1 Hour

**Comment by abs51295** [comment]
@chhavip There is no logout feature as of now, the user can disconnect the accounts from the profile and can connect them again if he wants to, so I think the user should be not be redirected to login page once he disconnects or logs out from a specific account.

**Comment by chhavip** [comment]
But this bug concerns that the login feature should not be there in case user has already logged in and is opening the app again. Otherwise he/she cannot progress from the screen.

**Comment by abs51295** [comment]
@chhavip I completely understand the bug. But you mentioned in the third point of the acceptance criteria: 
1. If User Logs Out, the Login Screen should be presented again on next opening of application

So I didn't get it, when does the user log out of the app? He just disconnects and reconnects the account per se.

**Comment by chhavip** [comment]
Is there a possibility that the user disconnects an account and does not immediately connect another but closes the app? In that case, Log In screen can be presented again.

**Comment by abs51295** [comment]
Yes, we can do that. But I was concerned if redirecting the user to the login screen once he disconnects both the accounts can lead to a bad user experience because those accounts are just for displaying in the profile so that other users can see the social profiles that the user has connected with his account. I was thinking of the following flow:

1. User opens the application for the first time.
2. User logs in to the application using any one of the social accounts.
3. We verify the details and register the user.
4. After verifying, we redirect the user to the schedule page.
5. Now, we allow the user to connect or disconnect his social accounts from the edit profile page.
6. In any case, we don't ask the user to sign up again because it would be annoying for the end user to repeat the whole process again.

**Comment by chhavip** [comment]
For now, this sounds like a good approach we can go with.

**Comment by chhavip** [comment]
Fixed via #34
